import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

const recursive = Recursive({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full grid">
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `	if (
						localStorage.theme === 'dark' ||
						(!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)
					) {
						document.documentElement.classList.add('dark');
					} else {
						document.documentElement.classList.remove('dark');
					}`,
					}}
				/>
			</head>
			<body className={cn('h-full', recursive.className)}>
				<main className="flex flex-col h-full min-h-[calc(100vh-3.5rem-1px)]">{children}</main>
				<Toaster />
			</body>
		</html>
	);
}
